#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rulebow
Version  : 0.4.0
Release  : 5
URL      : https://rubygems.org/downloads/rulebow-0.4.0.gem
Source0  : https://rubygems.org/downloads/rulebow-0.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-rulebow-bin
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-detroit
BuildRequires : rubygem-mast
BuildRequires : rubygem-notify
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# RULEBOW
[Homepage](http://rubyworks.github.com/rulebow) -
[Report Issue](http://github.com/rubyworks/rulebow/issues) -
[Source Code](http://github.com/rubyworks/rulebow) -
[IRC Channel](http://chat.us.freenode.net/rubyworks)

%package bin
Summary: bin components for the rubygem-rulebow package.
Group: Binaries

%description bin
bin components for the rubygem-rulebow package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rulebow-0.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-rulebow.gemspec

%build
gem build rubygem-rulebow.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rulebow-0.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rulebow-0.4.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/.index
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/bin/bow
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/demo/03_runner/01_applying_rules.md
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/demo/applique/ae.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/demo/applique/rulebow.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/demo/overview.md
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow.yml
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/true_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/digest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/fact.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/ignore.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/match.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/rule.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/ruleset.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/shellutils.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/system.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/lib/rulebow/watchlist.rb
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/man/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/man/ergo.1
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/man/ergo.1.html
/usr/lib64/ruby/gems/2.3.0/gems/rulebow-0.4.0/man/ergo.1.ronn
/usr/lib64/ruby/gems/2.3.0/specifications/rulebow-0.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/bow
