#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rulebow
Version  : 0.4.0
Release  : 4
URL      : https://rubygems.org/downloads/rulebow-0.4.0.gem
Source0  : https://rubygems.org/downloads/rulebow-0.4.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rubygem-rulebow-bin
BuildRequires : ruby
BuildRequires : rubygem-ae
BuildRequires : rubygem-detroit
BuildRequires : rubygem-mast
BuildRequires : rubygem-notify
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# RULEBOW
[Homepage](http://rubyworks.github.com/rulebow) -
[Report Issue](http://github.com/rubyworks/rulebow/issues) -
[Source Code](http://github.com/rubyworks/rulebow) -
[IRC Channel](http://chat.us.freenode.net/rubyworks)

%package bin
Summary: bin components for the rubygem-rulebow package.
Group: Binaries

%description bin
bin components for the rubygem-rulebow package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rulebow-0.4.0
gem spec %{SOURCE0} -l --ruby > rubygem-rulebow.gemspec

%build
gem build rubygem-rulebow.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rulebow-0.4.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rulebow-0.4.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Array/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Array/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Array/and_without_t-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Array/or_without_t-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Boolean/cdesc-Boolean.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Kernel/cli-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/cdesc-CLI.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/cli_parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/debug%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/debug%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/ensure_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/fire%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/fire%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/fire-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/fresh%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/fresh%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/init_project-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/print_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/print_rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/runner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/script%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/CLI/watch%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/cdesc-For.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/ruleset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/For/saved-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/cdesc-Digest.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/checksum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/clear_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/for_ruleset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/getruleset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/refresh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/save-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/saved-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Digest/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/cdesc-Fact.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Fact/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/FileFact/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/FileFact/cdesc-FileFact.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/FileFact/coerce-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/FileFact/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/FileFact/pattern-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/cdesc-Ignore.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/concat-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/fnmatch%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/replace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ignore/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Match/cdesc-Match.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Match/matchdata-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Match/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/cdesc-Rule.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/fact-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/invoke-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Rule/to_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/cdesc-Ruleset.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/chain%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/chain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/define_fact-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/define_task-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/desc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/docs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/fact-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/import-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/notify-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/parse_ruleset_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/require-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/rule-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/scripts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/state-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/watch%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/watch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Ruleset/watchlist-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/RootError/cdesc-RootError.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/autorun-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/build_chain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/cdesc-Runner.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/fresh%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/fresh%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/fresh_digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/home-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/ignore%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/locate_root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/monorun-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/ruleset_chain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/rulesets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/run_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/run_rules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/run_ruleset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/save_digests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/system-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/trial%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/trial%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/verify_ruleset%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/watch%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/Runner/watch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/cdesc-ShellUtils.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/directory%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/sh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/shell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/ShellUtils/sync-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/cdesc-System.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/digests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/home-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/import-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/parse_ruleset_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/rulebook-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/ruleset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/rulesets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/System/state_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/accept%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/accept-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/cdesc-WatchList.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/checksum-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/filter_accept-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/filter_ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/fnmatch%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/ignore%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/ignore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/read_digest-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/WatchList/root-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/Rulebow/cdesc-Rulebow.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/TrueClass/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/TrueClass/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/TrueClass/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/page-LICENSE_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/rulebow-0.4.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/.index
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/bin/bow
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/demo/03_runner/01_applying_rules.md
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/demo/applique/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/demo/applique/rulebow.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/demo/overview.md
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow.yml
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/boolean.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/core_ext/true_class.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/digest.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/fact.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/ignore.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/match.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/rule.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/ruleset.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/runner.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/shellutils.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/system.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/lib/rulebow/watchlist.rb
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/man/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/man/ergo.1
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/man/ergo.1.html
/usr/lib64/ruby/gems/2.2.0/gems/rulebow-0.4.0/man/ergo.1.ronn
/usr/lib64/ruby/gems/2.2.0/specifications/rulebow-0.4.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/bow
